### ISSUE TITLE
Master !== Crates.io

### ISSUE THREAD

**Issue by TomzBench** [ericseppanen/cddl-cat#6]
My repo compiles fine when i link to this repo via `git`... However when i try and pull from crates-io i get this error below.

crates-io advertises v0.6.1, and this master repo also advertises v0.6.1. but i suspect they are out of sync. Can you publish v0.6.2 perhaps?

```
error[E0277]: the trait bound `cddl_cat::parser::ParseError: std::cmp::Eq` is not satisfied
   --> src/util.rs:6:11
    |
4   | #[derive(Debug, PartialEq, Eq)]
    |                            -- in this derive macro expansion
5   | pub enum ValidateError {
6   |     Parse(ParseError),
    |           ^^^^^^^^^^ the trait `std::cmp::Eq` is not implemented for `cddl_cat::parser::ParseError`
    |
note: required by a bound in `AssertParamIsEq`
   --> /home/thomas/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/cmp.rs:313:31
    |
313 | pub struct AssertParamIsEq<T: Eq + ?Sized> {
    |                               ^^ required by this bound in `AssertParamIsEq`
    = note: this error originates in the derive macro `Eq` (in Nightly builds, run with -Z macro-backtrace for more info)
    ```

**Comment by ericseppanen** [comment]
Thanks for the bug report!

I use `cargo-release` to issue releases, so there shouldn't be any mismatch between the git tags and published crates. Just to check, I downloaded the released crate tarball and verified that it matches the `v.0.6.1` tag in git.

I'm a bit confused by the error message, because `ValidateError` does not `#derive(Eq)` in any published version of the crate. I did add it in the master branch, but that commit (cc38821f755490) added it to both `ValidateError` and `ParseError`. So I'm struggling to reproduce the problem.

**Comment by ericseppanen** [comment]
To test this further, I created a new project, and added the cddl-cat dependency in three different ways (crates.io version, git URL, and git URL with tag "v0.6.1"). I then built each of these with toolchain 1.68 and a recent nigthly (4a3c588b1 2023-03-14).

I wasn't able to reproduce the error in any of these combinations.

I'd like to understand how this happened, but so far I'm not able to figure it out because that error message implies something that doesn't look possible; there has never been a point in time where `ValidateError` tries to derive `Eq` but `ParseError` does not.

@TomzBench would you be able to provide any more detail about how to reproduce this? Does the error persist after a `cargo clean`?

**Comment by TomzBench** [comment]
hello @ericseppanen 

I did a cargo clean and then reproduced builds with both the crates.io and github repos.  I found that the hash for the github repo is: `2465d60974ab78e3`.  The hash for the crates.io repo is: `27c10991e8a2bd34`.

Also i took a look at the struct in question `ParseError` derive macros.  Here is is the impl of ParseError from crates.io:  

It appears to not derive `Eq` as the error suggests.
![parseerror-noeq](https://user-images.githubusercontent.com/20780378/227801847-d0dea791-f3e9-4d42-9591-09c374dbd857.png)

When I pull from master and note the ParseError definition:

Master does appear to derive Eq...
![parseerror](https://user-images.githubusercontent.com/20780378/227801879-0e802122-7bdd-4d48-b1f9-a29654887cf5.png)

It appears master has added the Derive `Eq` macro but this change is not published.  So it would be helpful if we do publish it. I think my test cases are perhaps triggering this error maybe. Only code that compares errors would trip this error I am guessing.  ...Happy to provide more info.

**Comment by ericseppanen** [comment]
> and then reproduced builds with both the crates.io and github repos

Can you please share the source code that causes the `ParseError: std::cmp::Eq` is not satisfied` error message?

> I found that the hash for the github repo is: 2465d60974ab78e3. The hash for the crates.io repo is: 27c10991e8a2bd34.

I would need more information about how you generated those values for them to be useful. Also, please specify whether you're referring to the git master branch or the git `v0.6.1` tag.

> Also i took a look at the struct in question ParseError derive macros. Here is is the impl of ParseError from crates.io:
>
> It appears to not derive Eq as the error suggests.

The 0.6.1 release does not derive `Eq` on `ValidateError`, so it should be irrelevant whether `ParseError` implements `Eq`.

I would like to understand the cause of the error. If you can supply an example of a project that fails to compile then I can make sure that the next release has resolved it.

**Comment by ericseppanen** [comment]
I just realized something else: deriving `PartialEq` or `Eq` on `ParseError` was actually a mistake: it would include a comparison against the `ctx` member too, which would probably not be what anyone wants.

In fact, I don't think that it's correct to use `==` to compare error structs, because it's not obvious what the result should be. Are two errors with the same kind but from different contexts equal? I don't think there's a clear answer.

I may need to redesign this error type to fix the mistake, and perhaps expose some `ValidateErrorKind` that has clear semantics.
In the meantime, I would suggest using pattern matching instead of equality to compare errors.

**Comment by TomzBench** [comment]
I'll review my project and see if i can find where the compare is being made. one moment plz!

**Comment by TomzBench** [comment]
@ericseppanen 

I agree you should not compare more complex error types  with `==`  and should prefer matching.

My project wraps the cddl-cat error type and was also unnecessarily deriving `PartialEq` and `Eq`. I think i was just greedily adding derive `Eq` because cddl-cat derived it as well, (but only in master).

Because my code worked with master and failed with crates.io, it led my instincts to just suggest pushing master. However, it would be more correct to remove `PartialEq` and `Eq` from the error types as you suggest!  thanks for digging deeper!
